### ISSUE TITLE
Help fast

### ISSUE THREAD

**Issue by Bakir0-dev** [AlDeen20/change.org-bot-by-aldeen#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/change.org-bot-by-aldeen/bot.py", line 15, in <module>
    web = webdriver.Chrome()#using chrome
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 92, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by Bakir0-dev** [comment]
There is a chromedriver in project repo

**Comment by ghost** [comment]
Estou com o mesmo erro no Linux...

**Comment by Zadude1** [comment]
Thank you Mr Essam
